### ISSUE TITLE
exposed functions

### ISSUE THREAD

**Issue by ksavvopoulos** [ksavvopoulos/javascript-collection#3]
Νομιζω οτι οι συναρτησεις που χρησιμοποιουνται και σαν private και γινονται και exposed θα επρεπε να οριζονται κανονικα σα private στην αρχη του κωδικα για να μην εχουμε την αναγκη να βαλουμε κωδικα κατω απο τον ορισμο του spyreqs.Για παραδειγμα η queryParams θα μπορουσε να γινει function queryParams(){...} και μετα στο utils να τη βγαλουμε με urlParamsObj:queryParams ή ακομα καλύτερα με queryParams:queryParams. Ετσι θα διαβαζεται καλυτερα ο κωδικας και δε θα χρειαζεται να ψαχνεις  το scope του spyreqs όταν χρησιμοποιειται σαν private.

**Comment by johnpan** [comment]
συμφωνώ, παίξε μπάλα
