### ISSUE TITLE
say function

### ISSUE THREAD

**Issue by ksavvopoulos** [ksavvopoulos/javascript-collection#4]
Καταρχην και για τη say πιστευω οτι πρεπει να οριστει σαν private και να γινει μετα exposed say:say.
Ενα δευτερο είναι οτι καθε φορα που καλειται ελεγχει για το αν υπαρχει η console.νομιζω οτι ο ελεγχος 8α πρεπει να γινεται μια φορα.θα μπορουσε ισως να οριστει μια var say και μετα να κανεις τον ελεγχο 
if (typeof window.console != 'undefined') { 
     say = function(what){window.console.log(what);}; 
} else κτλ

**Comment by johnpan** [comment]
σωστό έτσι ήθελα να το κανω αλλα την εγραψα βιαστικά για το Δουκα στο lms...
