### ISSUE TITLE
equal operator

### ISSUE THREAD

**Issue by ksavvopoulos** [ksavvopoulos/javascript-collection#5]
Προτείνω λόγω της ιδιορρυθμης  συμπεριφορας του "==" να αποφευγουμε τη χρήση του αν δεν υπάρχει κάποιος λόγος αλλιως να γραφουμε ενα σχολιο ωστε να ξερουμε οτι εγινε επιτηδες και για ποιο λογο.

**Comment by johnpan** [comment]
όπου το βάζω ξέρω ήδη ότι συγκρίνω ίδια types αλλά σωστή παρατήρηση για να μην προβληματίζεται και κάποιος που διαβαζει τον κωδικα.

**Comment by johnpan** [comment]
Το άλλαξα. Το == έχει το πλεονέκτημα ότι ο χρήστης του spyreqs μπορεί να δώσει στις παραμετρους που περνάει με json έναν αριθμό με ή χωρίς quotes... Πρέπει αυτό να το σκεφτούμε...
